### ISSUE TITLE
Dozens of orphan "Expo XDE Helper" processes

### ISSUE THREAD

**Issue by JulianKingman** [expo/xde#101]
Looking through my activity monitor, I found a whole bunch of orphan XDE helpers. I'm not sure how long they were there, just hangin' out, but I didn't even have XDE open.
![screen shot 2017-04-25 at 8 43 06 am](https://cloud.githubusercontent.com/assets/1566400/25386493/8f01f356-2995-11e7-90f7-58f8d307c6c3.png)

**Comment by brentvatne** [comment]
Moved to https://github.com/expo/expo/issues/177
