### ISSUE TITLE
Update Your Account page errors out

### ISSUE THREAD

**Issue by html5cat** [expo/xde#102]
Step 0: don't login into exponent for a while :) 
Step 1:
![screen shot 2017-04-26 at 12 12 45 pm](https://cloud.githubusercontent.com/assets/823890/25452224/b328f6e6-2a79-11e7-9c3a-49d3e104b18d.png)

Step 2:
![screen shot 2017-04-26 at 12 13 21 pm](https://cloud.githubusercontent.com/assets/823890/25452238/c33f7f64-2a79-11e7-8496-faed3d72f664.png)

**Comment by html5cat** [comment]
Signing out and signing back in seems to resolved it.

**Comment by brentvatne** [comment]
@skevy - this is fixed now right?

**Comment by brentvatne** [comment]
this is fixed and will land in our next xde release!
