### ISSUE TITLE
Sometimes starts on port 80, problems ensue

### ISSUE THREAD

**Issue by JulianKingman** [expo/xde#103]
Sometimes XDE will start on port 80, which the simulator doesn't seem to like. I can't reliably say why, but it might happen while having the exponent app open, quitting, and then restarting XDE.

**Comment by brentvatne** [comment]
Hello! Thanks for the report. It's not clear to me what is happening here, there's not much we can do without more details. If you manage to get into this situation again please try to recall the steps so we can get a repro case! Thanks :)

**Comment by JulianKingman** [comment]
I'll pay attention if it happens again, I tried quitting XDE and reopening with the app running, but that didn't trigger it.

**Comment by brentvatne** [comment]
cool, closing this and if you can repro please open another issue
