### ISSUE TITLE
Use an environmental variable to switch between 'prod' and 'dev' mode

### ISSUE THREAD

**Issue by wwwillchen** [expo/xde#105]
I'd like to have two entry points for my app - one for dev/test usage (e.g. mock DB connection) and one for production usage (e.g. real DB connection).

I saw in [CRNA](https://github.com/react-community/create-react-native-app/pull/125/files) you can actually pass in an environmental variable and do some type of switch logic. Is there a way to pass an environmental variable through XDE or another way of creating two entry points? I initially tried creating a sub-project called 'test-app', but it seems cumbersome as XDE expects to be in the root of a project (e.g. package.json, node_modules).

For now, I've just been commenting out one line in the entry file to switch between prod and dev mode (e.g. `import ... from 'production_entrypoint'`)

Thanks for all the work you all are doing. It's been awesome using Expo so far.

**Comment by dikaiosune** [comment]
If you start XDE from the command line (`xde .` inside your project folder) it will pick up any environment variables prefixed with `EXPO_` and pass them to your app. Note that these environment variables won't be available when you publish your app, and they also can't affect which imports are included in your bundle, but they do allow you to select which components are mounted at runtime, for example.

**Comment by dikaiosune** [comment]
Also, sorry if this was curt! I'm super glad you're enjoying using Expo!

**Comment by wwwillchen** [comment]
No worries - thanks for your response!
