### ISSUE TITLE
Initialised app shows error when opening in the iOS emulator

### ISSUE THREAD

**Issue by itsashis4u** [expo/xde#107]
The app which I created using XDE runs into the error in the screenshot when running in iOS emulator.
Also, I am unable to open the project on Android device, it gets stuck in the `Fetching JS Bundle` window and nothing else shows up.
xde version: 2.17
Expo app: 1.15.1

<img width="1143" alt="XDE Error" src="https://cloud.githubusercontent.com/assets/4126695/25732717/495cffa2-3170-11e7-914e-6914847bb209.png">

**Comment by brentvatne** [comment]
hi there! this can happen if the simulator is in a bad state, unfortunately it has nothing to do with expo -- you'll need to run "Reset Content and Settings" in the simulator.

**Comment by itsashis4u** [comment]
Thanks @brentvatne !

**Comment by jesseruder** [comment]
My guess it that this was an intermittent error with our tunnel provider. Does this happen consistently after pressing "Restart"?

**Comment by itsashis4u** [comment]
@jesseruder It does many times I start the emulator. Comment from @brentvatne helped, but this error still does come up few times in between.
