### ISSUE TITLE
[Windows]Cannot find entry file main.js in any of the roots

### ISSUE THREAD

**Issue by mpetrunic** [expo/xde#110]
I'm having a issue with starting an existing expo project on windows 7.
After line "Opening on Android device" I'm getting following error:
```
5:29:13 PM
Opening on Android device
5:29:29 PM
NotFoundError: Cannot find entry file main.js in any of the roots: ["D:\\workspace\\expo\\jf-card-sharing"]
(node:10352) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

You can test and check [source code](https://github.com/KSET/jf-card-sharing).

**Comment by brentvatne** [comment]
hello! do you have a file called main.js? please create a new issue on https://github.com/expo/expo with some more information information about your project :)

**Comment by brentvatne** [comment]
oh sorry I just noticed that you posted the sourcecode.

**Comment by brentvatne** [comment]
@mpetrunic - I cloned your project on my mac and it worked as expected. I don't have a windows 7 machine to test this on :( do other projects work for you or is it only this one?

**Comment by brentvatne** [comment]
@mpetrunic - I moved this issue to https://github.com/expo/expo/issues/182 because we are consolidating our issues onto the main expo/expo repo, please reply there :)
