### ISSUE TITLE
Install Expo in genymotion emulator 

### ISSUE THREAD

**Issue by DaoHuyTuan** [expo/xde#111]
i was try use expo and install expo in android studio emulator , it was success 
but when i install expo to genymotion emulator , it show me error 
i try fix thi error haft of day but no use 
can anyone help me with this ?? 
i'm newbie , and sorry about bad english but please help 

Thanks you for everything 
![captuvfegvre](https://cloud.githubusercontent.com/assets/26370399/25792516/387ec228-33f1-11e7-9c52-6ef690aef0d5.PNG)

**Comment by brentvatne** [comment]
hi! looks like you posted this to the forum, where @ccheever gave you an answer
