### ISSUE TITLE
Documentation incomplete on converting an existing project to expo

### ISSUE THREAD

**Issue by kitsune7** [expo/xde#113]
Currently the documentation leaves a lot of vital steps like creating an `exp.json` file, updating to the proper versions for react and react native, and adding expo to `package.json`. There might even be more steps that need to be taken, but I know at least these ones are needed even though they're not mentioned in the readme.

**Comment by brentvatne** [comment]
Tracking the fix for this issue here https://github.com/expo/xde/issues/113

**Comment by arapocket** [comment]
Any plans to update the documentation?
