### ISSUE TITLE
Unable to delete a project after download was cancelled mid way

### ISSUE THREAD

**Issue by ShashankaNataraj** [expo/xde#114]
I stopped a project download mid way because it was taking too much time and I'm now stuck with this entry on my screen, which Im neither able to click nor remove...

<img width="319" alt="screen shot 2017-05-19 at 5 01 15 pm" src="https://cloud.githubusercontent.com/assets/650317/26246052/cf25abf8-3cb4-11e7-96bc-f41e5e7b8c63.png">

Any ideas on how I would go about solving this?

**Comment by dikaiosune** [comment]
If you delete the file `$HOME/.expo/xde-recent-exps.json` with XDE not running, it should be gone when you start it back up.

**Comment by ShashankaNataraj** [comment]
@dikaiosune Thank you!
