### ISSUE TITLE
New project - loading never finish

### ISSUE THREAD

**Issue by NemanjaManot** [expo/xde#115]
In my Linux machine i have some trouble.

I downloaded latest version of XDE (xde-2.18.0-x86_64.AppImage) for Linux (ubuntu 16.04 LTS).
I open with `chmod a+x xde-2.18.0-x86_64.AppImage` and `./xde-2.18.0-x86_64.AppImage` , but loading is never finish, when i click Project / New Project...

I have no idea what is wrong...

![expoloading 1](https://cloud.githubusercontent.com/assets/18553180/26573076/a672829c-451c-11e7-8f32-a6f31fd6e0df.jpg)

**Comment by charlesvinette** [comment]
@NemanjaManot Hello! Can you give me a little more details on what is happening? Are you actually able to give your new project a name or as soon as you click on Project -> New Project it hangs?

**Comment by NemanjaManot** [comment]
@charlesvinette Hello! 
No, after opening Expo XDE and click Project -> New Project this happens. More people on Linux have same problem like me.
I can start CRNA project from terminal... but Expo project from XDE - no.

**Comment by charlesvinette** [comment]
@NemanjaManot Thanks for getting back to me, we will look into it.

**Comment by brentvatne** [comment]
The fix for this issue is being tracked here, it will be available in our next XDE release: https://github.com/expo/expo/issues/179
