### ISSUE TITLE
can not create project

### ISSUE THREAD

**Issue by wind4gis** [expo/xde#120]
I am using win7 with framework 4.5.x
while i start to create my project, it shows either 'service time out' or 'EPERM: operation not permitted, access 'C:\Users\Administrator\.expo\starter-app-cache\blank-17.0.1.tar.gz'
can anybody tell me how to fix it

**Comment by brentvatne** [comment]
hello! please follow the issue template:

```
We're looking to keep questions on our forums and bug reports on our main Expo repo -- please choose whichever you feel is more appropriate for your issue:

* Post in our community forums (log in with your Expo developer account): https://forums.expo.io/c/help
* File a bug on the Expo repo: https://github.com/expo/expo/issues/new
* Request a feature on Canny: https://expo.canny.io/feature-requests

Thanks for reporting the issue you found with XDE!
```

additionally, we do not support windows 7 unfortunately (neither does microsoft) :(

**Comment by wind4gis** [comment]
ok..i am so sad..

**Comment by brentvatne** [comment]
@wind4gis - sorry :( you can use `exp`, our cli tool instead. `npm i -g exp`

**Comment by wind4gis** [comment]
@brentvatne can i use exp debugging with webstorm?
can it hot load?

**Comment by brentvatne** [comment]
maybe, I have never used webstorm so I can't say. let me know what you find!
