### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by Stormsher** [expo/xde#124]
Are there any way to install XDE on windows 10 without admin rights?
Or maybe smbody have ZIP archive with last XDE version?

**Comment by brentvatne** [comment]
Hi! Sorry for the late reply, we don't check this repo for issues. As the issue template suggests, this is not the right place to post issues.

----------------------------------------------------------------------------

We're looking to keep questions on our forums and bug reports on our main Expo repo -- please choose whichever you feel is more appropriate for your issue:

* Post in our community forums (log in with your Expo developer account): https://forums.expo.io/c/help
* File a bug on the Expo repo: https://github.com/expo/expo/issues/new
* Request a feature on Canny: https://expo.canny.io/feature-requests

Thanks for reporting the issue you found with XDE!
