### ISSUE TITLE
Error when publishing

### ISSUE THREAD

**Issue by tysoncadenhead** [expo/xde#125]
I am able to run my app on my device without an issue, however, when I try to publish it in XDE, I am getting this error:

<img width="591" alt="screen shot 2017-07-16 at 12 07 24 am" src="https://user-images.githubusercontent.com/355354/28244801-d3935acc-69ba-11e7-8d3e-27f75b4e3ad0.png">

Here is my app.json:

```
{
  "expo": {
    "name": "voice-choice",
    "description": "VoiceChoice",
    "slug": "voice-choice",
    "privacy": "public",
    "sdkVersion": "18.0.0",
    "version": "1.0.0",
    "orientation": "landscape",
    "primaryColor": "#DA5D36",
    "icon": "./assets/images/app-icon.png",
    "loading": {
      "icon": "./assets/images/loading.png",
      "hideExponentText": false
    },
    "packagerOpts": {
      "assetExts": ["ttf", "mp4"]
    },
    "ios": {
      "supportsTablet": true
    }
  }
}
```

and I am using these dependency versions:

```
"expo": "^18.0.4",
"react": "16.0.0-alpha.12",
 "react-native": "https://github.com/expo/react-native/archive/sdk-18.0.1.tar.gz",
```

I'm not exactly sure how to go about debugging the error, so any pointers would be helpful in that regard.

**Comment by brentvatne** [comment]
does the app run locally? it looks like the packager is just throwing a server error

**Comment by brentvatne** [comment]
also, as the issue template suggests this repo isn't intended for posting issues, we try to consolidate into https://github.com/expo/expo/issues/411 or our forums https://forums.expo.io
