### ISSUE TITLE
chrome/safari give security warning on XDE for mac download link 

### ISSUE THREAD

**Issue by grigored** [expo/xde#127]
<img width="1680" alt="screen shot 2017-07-25 at 3 51 20 pm" src="https://user-images.githubusercontent.com/12827406/28572931-8d1cba2c-7151-11e7-8f0e-cda5d449c646.png">

**Comment by hexrcs** [comment]
I can reproduce in FireFox as well.

**Comment by ide** [comment]
It looks like something got updated on Google's side for this GitHub S3 bucket, which is affecting several projects:
- https://www.bleepingcomputer.com/news/security/some-github-downloads-blocked-in-chrome-and-firefox-due-to-safe-browsing-warning/
- https://github.com/yarnpkg/yarn/issues/4019
- https://github.com/lmenezes/cerebro/issues/184
- https://news.ycombinator.com/item?id=14845577

I'm not able to reproduce this on my computer but could you try downloading the Mac .zip link instead?

**Comment by hexrcs** [comment]
Thanks for the news links, just tried downloading the DMG file for mac again and didn't see a warning this time. The problem seems to be fixed.

**Comment by ide** [comment]
Thanks for the update, I'll close this issue then.
