### ISSUE TITLE
Downloading xde Error

### ISSUE THREAD

**Issue by Mohammed-Saeed** [expo/xde#128]
Hay Gays I Have Problem With Downloading The Source Of xde From The Website

after stop Downloading 

I always Had this Error

This XML file does not appear to have any style information associated with it. The document tree is shown below.

<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<X-Amz-Expires>300</X-Amz-Expires>
<Expires>2017-07-28T22:03:35Z</Expires>
<ServerTime>2017-07-28T22:18:10Z</ServerTime>
<RequestId>AE3AF6AC6C80A3AC</RequestId>
<HostId>
epL/3sAiZJ1xEPxXe1dKGcbgwTxZPYVqcLtxcrjVsPsYNw5rpiJrFPHCynMynkFpkZenvV/F1eI=
</HostId>
</Error>

**Comment by brentvatne** [comment]
please follow issue template and create this issue on https://github.com/expo/expo/issues :) also provide more information.
