### ISSUE TITLE
xde can not work

### ISSUE THREAD

**Issue by kinglywork** [expo/xde#130]
Hi , 
I just used xde yesterday normally, and today I can not use xde to do anything, xde just show loading icon whether when I create new project or open exists project. the log is here: 

{"name":"expo","hostname":"Yis-MacBook-Pro.local","pid":3006,"level":50,"err":{"message":"There was a problem understanding the server. Please try again.","name":"Error","stack":"Error: There was a problem understanding the server. Please try again.\n    at /Applications/Expo XDE.app/Contents/Resources/app/node_modules/xdl/build/ApiV2.js:162:23\n    at Generator.throw (<anonymous>)\n    at step (/Applications/Expo XDE.app/Contents/Resources/app/node_modules/xdl/build/ApiV2.js:42:191)\n    at /Applications/Expo XDE.app/Contents/Resources/app/node_modules/xdl/build/ApiV2.js:42:402\n    at process._tickCallback (internal/process/next_tick.js:103:7)"},"msg":"There was a problem understanding the server. Please try again.","time":"2017-08-08T02:52:16.790Z","v":0}

any idea to fix this problem?

**Comment by dikaiosune** [comment]
Hi! Can you please open this again at https://github.com/expo/expo, as requested in the issue template? Could you also provide some information about your system, like what version of macos you have, the version of xde you're using, etc.? Thanks!

**Comment by kinglywork** [comment]
Now I can open pure js project. but the detached project still not open.

MacOS: 10.12.6
Xde: 2.19.3

**Comment by kinglywork** [comment]
I debugged the code of exp and xdl and I found the process hung at getting schema from https://exp.host/--/xdl-schema/19.0.0.
and getting versions from
https://exp.host/--/api/v2/versions

**Comment by ide** [comment]
Do you perhaps have an HTTP proxy in the way? If you do, you can set the http_proxy and https_proxy env cars and XDE should honor them.

**Comment by kinglywork** [comment]
@ide I access network through vpn, maybe it has something to do with the network environment.
