### ISSUE TITLE
[SITE expo.io] connect ETIMEDOUT on download Page

### ISSUE THREAD

**Issue by mickadoua** [expo/xde#132]
today i have this message when i tried to download  EXPO XDE 

https://xde-updates.exponentjs.com/download/win32
> connect ETIMEDOUT 192.30.253.116:443

**Comment by mickadoua** [comment]
Update, his is ok now ...  i dont know if I must close this issue

**Comment by ide** [comment]
I think this was because GitHub releases had some temporary issues.
