### ISSUE TITLE
Third Party Library Native Changes Issue

### ISSUE THREAD

**Issue by sachinharpalani** [expo/xde#134]
I am currently using a expo app that was created through lein new expo. I need to integrate a third party library(clevertap) that requires me to make changes to native android files. I cannot access android files when working through expo. If i want to use this library, is there a work around where i can change native code and still use expo xde?

**Comment by psycura** [comment]
Similar question - if I'll make eject with expo api from CRNA, I will be able to use custom native modules and the expo api possibilities?

**Comment by dikaiosune** [comment]
Hi! Please make sure to read the issue template. To answer your question, yes you can customize native code. I would recommend searching our [docs] (https://docs.expo.io) for "ExpoKit."
