### ISSUE TITLE
Expo not deploying to iOS simulator

### ISSUE THREAD

**Issue by Gringox** [expo/xde#135]
Hi,

Yesterday I got an update from expo to version 2.20.1 (2.20.1) and idk why but it broke the deployment to iOS simulator (haven't test it on Android emulator yet), devices still work though both Android and iOS.

The React Native Packager console shows two errors, one after scanning folders:

```
Error starting tunnel: Error: Starting tunnels timed out
```

And the other one when doing the deploy to iOS simulator:

```
Error installing or running app. Error: Couldn't connect to the server, check your internet connection.
```

Any help?

**Comment by brentvatne** [comment]
Hi there! As per the issue template, please post issues to https://github.com/expo/expo/issues
