### ISSUE TITLE
Unable to create Project From Template

### ISSUE THREAD

**Issue by shabbir1993** [expo/xde#136]
I've installed expo on windows, 
I've tried to create project from template several times but it just hangs out on either "Downloading Project Files" or "Extracting Files" or gives me following error : 
"EPERM: operation not permitted, access 'C:\Users\shabbir\.expo\starter-app-cache\blank-20.0.1.tar.gz'"

I've tried to run expo as administrator as well but still same problem
I've also tried creating project after clearing xde cache but the issue persists.

Thanks for your help in advance.

**Comment by ThalaHemanth** [comment]
Same Issue

**Comment by MohamedHamed83** [comment]
Same issue

**Comment by D1111111** [comment]
Same here :+1:

**Comment by YulianD** [comment]
same issue, help please

**Comment by brentvatne** [comment]
Hi there! As per the issue template, please post issues to https://github.com/expo/expo/issues
