### ISSUE TITLE
Logging does not support any special syntax or collapse/expand

### ISSUE THREAD

**Issue by kbrandwijk** [expo/xde#138]
I use `redux-logger`, which is great for logging in the browser. However, logging in the XDE logging window is... less nice. Could anything be done to support syntax commands for logging, like in the browser? Also, being able to collapse data structures like in Chrome (for example) would absolutely make the logging window a lot more usable.

![image](https://user-images.githubusercontent.com/852069/30564140-61b584f6-9cc4-11e7-86c8-51b24699dd00.png)

**Comment by brentvatne** [comment]
Hi there! As per the issue template, please post issues to https://github.com/expo/expo/issues
