### ISSUE TITLE
Unable to make new Expo account

### ISSUE THREAD

**Issue by ZachCurtis** [expo/xde#141]
Attempted to make a new account with command prompt run as administrator and getting the error "[exp} Error registering user: An unknown error occured"

Getting the same message attempting to create account or link github account on the expo site.

**Comment by jimmylee** [comment]
Hey @ZachCurtis can you let me know the username/email you are trying use? Love to help.

**Comment by ZachCurtis** [comment]
@jimmylee ZachCurtis/z51515151@gmail.com. I'm getting the same error message when attempting to sign up via expo ios app.

**Comment by jimmylee** [comment]
ZachCurtis, can you please go to https://expo.io/login and click Sign in with GitHub? That will help you complete your github signup.

I'm sorry you ended up in this situation, its because your account exists.

**Comment by ZachCurtis** [comment]
@jimmylee probably from the attempt after command prompt didn't work. "An unknown error occurred." when trying to sign in with github. Created a new email and made an account with that. Thanks for the help.
