### ISSUE TITLE
 Failed to publish package: API Response Error: SCHEMA_VALIDATION_ERROR

### ISSUE THREAD

**Issue by appjitsu** [expo/xde#142]
![screen shot 2017-10-11 at 7 00 42 am](https://user-images.githubusercontent.com/10903600/31439493-eec331ce-ae51-11e7-9f44-c54b6cd168a5.png)

**Comment by dikaiosune** [comment]
Hi! Please note in the new issue template that we've asked for bugs to be reported on https://github.com/expo/expo. Can you open this issue there and also provide your XDE version, operating system, and the (non-private-key) contents of `app.json`?

**Comment by appjitsu** [comment]
ref: https://github.com/expo/expo/issues/763
