### ISSUE TITLE
Install error on Mac OS High Sierra

### ISSUE THREAD

**Issue by kot-ezhva** [expo/xde#143]
Hi!
First, sorry for my English :-)
When I mounted image, I see empty window.
![image](https://user-images.githubusercontent.com/15121885/31460533-714d1902-aecf-11e7-8533-be41e07434af.png)
After reopening mounted image, I see XDE icon and Application folder.
![image](https://user-images.githubusercontent.com/15121885/31460611-b0ed7822-aecf-11e7-8a10-9b3c0fce7c70.png)
But after drag icon to folder, I see error message.

![image](https://user-images.githubusercontent.com/15121885/31460772-17561ace-aed0-11e7-8791-0f7c5ec55fb1.png)
"The operation could not be completed because one or more of the required objects could not be found. (Error code -43)"
What could be the problem?

 Mac OS high sierra (10.13 (17A405))

**Comment by brentvatne** [comment]
Hi there!

Sorry you're having this issue :( Can you repost it to https://github.com/expo/expo/issues? We try to keep all of our issues there (we suggest it in the issue template message too).

Thanks!
