### ISSUE TITLE
blank window in win 10

### ISSUE THREAD

**Issue by Jancat** [expo/xde#144]
I was first installing xde in win 10, and it show a blank window after startup. 
![image](https://user-images.githubusercontent.com/11827786/31498930-df9f27da-af95-11e7-9854-a3b373e5d26f.png)

I clicked View > Reload and  it showed Sign In Page in seconds and then disappered.
![image](https://user-images.githubusercontent.com/11827786/31499033-2314a5da-af96-11e7-9b15-62e95ac8a001.png)

I had reinstalled but it still the same.

**Comment by Jancat** [comment]
![image](https://user-images.githubusercontent.com/11827786/31499233-cddad82c-af96-11e7-8dff-544d3bee05ca.png)

**Comment by brentvatne** [comment]
Hi!

Please see the issue template, which asks that you post issues to the github.com/expo/expo repo:

```
We're looking to keep questions on our forums and bug reports on our main Expo repo -- please choose whichever you feel is more appropriate for your issue:

* Post in our community forums (log in with your Expo developer account): https://forums.expo.io/c/help
* File a bug on the Expo repo: https://github.com/expo/expo/issues/new
* Request a feature on Canny: https://expo.canny.io/feature-requests

Thanks for reporting the issue you found with XDE!
```
