### ISSUE TITLE
Android status bar on older versions

### ISSUE THREAD

**Issue by rulgf** [expo/xde#145]
Hi,

I'm using the androidStatusBar key in my app.json but it seems it only works on newer versions of android

Android Version 6.0:
![_20171012_113417](https://user-images.githubusercontent.com/9823771/31507933-1a8686d0-af42-11e7-822b-fe96ea8d8c00.JPG)

Android Version 4.4.4:
![img_20171012_113313](https://user-images.githubusercontent.com/9823771/31507972-3d244830-af42-11e7-865a-80f92d414fd5.JPG)

My androidStatusBar:
```
"androidStatusBar": {
        "barStyle": "dark-content",
        "backgroundColor": "#eeeeee",
    },
```

**Comment by brentvatne** [comment]
Hi!

Please see the issue template, which asks that you post issues to the github.com/expo/expo repo:

```
We're looking to keep questions on our forums and bug reports on our main Expo repo -- please choose whichever you feel is more appropriate for your issue:

* Post in our community forums (log in with your Expo developer account): https://forums.expo.io/c/help
* File a bug on the Expo repo: https://github.com/expo/expo/issues/new
* Request a feature on Canny: https://expo.canny.io/feature-requests

Thanks for reporting the issue you found with XDE!
```
