### ISSUE TITLE
XDE Can't launch app on ios simulator

### ISSUE THREAD

**Issue by asciifaceman** [expo/xde#148]
XDE: Version 2.21.0 (2.21.0)
Simulator: Version 10.0 (SimulatorApp-829.6 (iPhone X 11.0)
MacOS Sierra 10.12.6

When choosing to launch the ios simulator from the XDE window, it seems to only load a json dump in a browser and that is it. 

I have tried using the Install on simulator options to make sure everything was present.

<img width="417" alt="screen shot 2017-10-26 at 9 38 48 pm" src="https://user-images.githubusercontent.com/1619591/32088390-bb1f84e2-ba97-11e7-9a0b-3b24b57e7726.png">

<img width="517" alt="screen shot 2017-10-26 at 9 39 18 pm" src="https://user-images.githubusercontent.com/1619591/32088161-2a904d86-ba96-11e7-87bb-2d4b9dd781c0.png">

No other logs are present, except for at the ios system level in which it spews through a few thousand lines similar to:

```
__MKBasicMapViewAccessibility_super is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/AccessibilityBundles/VectorKit.axbundle/VectorKit (0x12eecfe70) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/AccessibilityBundles/MapKit.axbundle/MapKit (0x12ef2cf80). One of the two will be used. Which one is undefined.
```
and

```
Oct 26 21:34:59 core com.apple.CoreSimulator.SimDevice.94299B8A-C029-46B7-922D-DC9DDE1B0F15[67959] (com.apple.AnnotationKit.MigratorService): Unknown key for Boolean: EnableTransactions
```

If I return to the main expo screen in the simulator the project does not show up in the previous project list.

**Comment by brentvatne** [comment]
Hello! It looks like you may have accidentally changed the protocol from `exp` to `http`

If you open up the project again, press the gear icon beside the url, and change from http to exp, then open the app in iOS simulator again, it will work.

I have prepared this elaborate diagram to help with the issue, hope it is useful ;)

<img width="796" alt="screen shot 2017-11-03 at 4 41 19 pm" src="https://user-images.githubusercontent.com/90494/32399733-d7cc114a-c0b5-11e7-9032-dbce3a1f8572.png">
