### ISSUE TITLE
Kaspersky Internet Security Trojan warnings during Expo v2.22.1 installation

### ISSUE THREAD

**Issue by codefl0w** [expo/xde#155]
Expo notified me that it needs updating. After it downloaded the update and attempted to install, Kaspersky went crazy and deleted the installer. Then I manually downloaded the installer, paused Kaspersky and successfully installed and opened Expo. As soon as I resumed Kaspersky, it went crazy again and deleted the Expo launcher, installer, and reverted firewall policies Expo apparently changed. I attached a screenshot of Kaspersky's actions during the 2nd attempt I mentioned.

![capture](https://user-images.githubusercontent.com/5368961/33252021-46c2514e-d2f0-11e7-835d-e67306f56d39.PNG)

**Comment by brentvatne** [comment]
Hi there! Maybe you can reach out to Kaspersky and see what is going on. You're welcome to inspect the source of XDE and you will see that there are no such things inside of the application. Sounds like a false positive to me.
