### ISSUE TITLE
iOS Simulator not installed after reinstalling Xcode

### ISSUE THREAD

**Issue by theobouwman** [expo/xde#156]
I've reinstalled Xcode but I'm still getting this error message when trying to run on an iOS Simulator:
```
Simulator not installed. Please visit https://developer.apple.com/xcode/download/ to download Xcode and the iOS simulator. If you already have the latest version of Xcode installed, you may have to run the command `sudo xcode-select -s /Applications/Xcode.app`.
```
Even after the suggested command the error keeps coming back.

**Comment by fson** [comment]
Can you open Xcode and check the following:

1. If it pops up "Install additional required components" press "Install".
<img width="592" alt="screen shot 2017-11-28 at 17 01 09" src="https://user-images.githubusercontent.com/497214/33326544-f0a10eee-d45d-11e7-85cc-1374d248ddc3.png">

2. Open *Xcode > Preferences > Locations* and check that "Command Line Tools" dropdown points to your Xcode version.
<img width="912" alt="screen shot 2017-11-28 at 17 05 17" src="https://user-images.githubusercontent.com/497214/33326709-533f1974-d45e-11e7-8d61-4b686eb9213c.png">
