### ISSUE TITLE
Indecator when app is deploying

### ISSUE THREAD

**Issue by exhesham** [expo/xde#158]
I am working with Expo XDE Desktop on windows for android mobile development.

Problem: When i save a change, there is no deployment status or progress bar on the Desktop app neither the Android App

How can i know that the app deployment is in progress, failed or finished?

**Comment by fxfactorial** [comment]
Hi, do you mean for live reloading ? Do you see bottom of app in simulator ?

**Comment by exhesham** [comment]
I see the live reloading only on the next scenario:
1- restart the app
2- Device -> Open on android

However, it doesn't appear on live reloading.

I am using Android G8

**Comment by brentvatne** [comment]
duplicate of this issue https://github.com/expo/expo/issues/1068
