### ISSUE TITLE
Running `npm install <x>` and then restarting the packager sometimes hangs

### ISSUE THREAD

**Issue by ide** [expo/xde#56]
wli reported an issue where installing a dependency and then clicking Restart can cause the packager to hang. Live Reload and not HMR is enabled.

Sometimes when the packager does restart it takes 90 seconds saying "Restarting project and clearing packager cache (Hold shift while clicking restart to avoid clearing cache)." and then the rest finishes quickly in two seconds.

OS: Ubuntu 16.04
Watchman: externally installed, 4.1.0
XDE: HEAD (as of today)

**Comment by jesseruder** [comment]
4.1.0 is an old version of Watchman so that might be the problem.
