### ISSUE TITLE
Safari  devtools + Exponent-in-iOS-simulator hangs on auto-reload.

### ISSUE THREAD

**Issue by krstffr** [expo/xde#65]
If I open the iOS simulator via the Exponent Mac App and then use the Safari devtools to access the Simulator -> JsContext, both Safari and the Exponent app (inside the simulator) hangs on code reload, forcing me to reload the app in the simulator as well as start Safari again (and go into the dev tools). Not the biggest deal, but still annoying.

Safari Version 10.0 (11602.1.50.0.10)
Mac os 10.11.6 (15G1004
Exponent Mac App Version 2.8.0 (2.8.0
Simulator Version 10.0 (SimulatorApp-700.5.3

**Comment by jesseruder** [comment]
Do you know if this happens in raw React Native?

**Comment by krstffr** [comment]
I don't know I'm afraid, and I don't have a raw React Native project around to test :(

**Comment by brentvatne** [comment]
So I tried this with a project created from `react-native init` and in an Expo project and they behave the same -- this was maybe a bug with an old version of react-native.

That said, there appears to be no workaround for the debugger closing each time the app reloads. The JSContext is torn down and re-created each time, with an Expo app or a plain react-native app. You could probably write some AppleScript to handle this for you though!
