### ISSUE TITLE
Unable to Connect on Android AVD

### ISSUE THREAD

**Issue by peterwanggg** [expo/xde#70]
I get the authorization error below using an AVD despite having done following:

1. Followed the directions in the error message and enabled USB debug mode
2. Ensured the adb shows it as a device: $ANDROID_HOME/platform-tools/adb devices
3. Removed Exponent and installed (metadata was still there, how do I do a clean install?)

This computer is not authorized to debug the device. Please follow the instructions here to enable USB debugging:
https://developer.android.com/studio/run/device.html#developer-device-options. If you are using Genymotion go to Settings -> ADB, select "Use custom Android SDK tools", and point it at your Android SDK directory.

**Comment by jesseruder** [comment]
XDE might now have been able to find your `adb` path. Can you make sure you can run `adb` from a terminal and then run `npm i -g exp && exp path`.

**Comment by zachariahtimothy** [comment]
@jesseruder I installed Expo, then installed Genymotion and followed the Genymotion guide. 
- Set ADB Path (Genymotion says it is a good path)
- Ran ````npm i -g exp && exp path````
When I run which adb it shows /usr/local/bin which for sure appears when I echo $PATH. 
I still get the error:
"Couldn't start project on Android: Error running adb: No Android device found. Please connect a device and follow the instructions here to enable USB debugging:
https://developer.android.com/studio/run/device.html#developer-device-options. If you are using Genymotion go to Settings -> ADB, select "Use custom Android SDK tools", and point it at your Android SDK directory."

Any tips on moving past this?

**Comment by brentvatne** [comment]
This guide should work for most people: https://docs.expo.io/versions/v18.0.0/guides/genymotion.html
