### ISSUE TITLE
Unable to start project when opened from a cloned repo

### ISSUE THREAD

**Issue by itsashis4u** [expo/xde#81]
Steps:
- Created a new project on XDE (Mac)
- Pushed to GitHub
- Cloned on a Linux Machine
- Did a `yarn install`
- Opened the project on XDE (Linux)

**Ran into error. Won't start**
![screenshot from 2017-03-10 11 46 30](https://cloud.githubusercontent.com/assets/4126695/23784367/8c341fc8-0587-11e7-812d-da4fb2cb2d73.png)

**Comment by jesseruder** [comment]
Hey we had a bug where one of our linux download links pointed to an old version of xde. Can you download from this link https://xde-updates.exponentjs.com/download/linux-x86_64 and try again?

**Comment by itsashis4u** [comment]
@jesseruder Sure, will give it a try and post if everything goes fine.

**Comment by dikaiosune** [comment]
Hi! Since we haven't heard back from you I'll close this, assuming the update to XDE worked. Please comment again if you're still having problems.
