### ISSUE TITLE
Debugger logs don't list source (shows as Logs:160)

### ISSUE THREAD

**Issue by JulianKingman** [expo/xde#82]
Any console output in the JS debugger just shows as being from `Logs: 160`, is this expected?

![screen shot 2017-03-15 at 3 27 57 pm](https://cloud.githubusercontent.com/assets/1566400/23967109/1410910a-0994-11e7-9567-3d23c5c67cd6.png)

**Comment by brentvatne** [comment]
Confirmed that this is an issue and moved it to https://github.com/expo/expo/issues/181
