### ISSUE TITLE
Clicking on project (or restart project) too many times = ip address issues

### ISSUE THREAD

**Issue by JulianKingman** [expo/xde#83]
So it seems that by default XDE uses 1900 for the simulator and 1901/1902 for the packager. The porblem is if I accidentally click something twice, whether it's 'send to simulator', 'restart', or anything, XDE checks and sees that the IP address is taken (because it's still running), then starts a new one, and tries to run on that. That usually leads to conflicts between what the simulator is looking for and what the packager is running on, and I get some sort of error and have to quit everything and restart. It's nice that XDE checks if IP addresses are in use, but in most cases (all cases, for me), the IP address is in use because XDE was using it, and it could either wait for it to close, or close it forcefully, then use the same one, and avoid the issues.

![screen shot 2017-03-18 at 9 01 08 am](https://cloud.githubusercontent.com/assets/1566400/24072201/96f769dc-0bb9-11e7-90ee-03320ddc48dd.png)

**Comment by ide** [comment]
Thanks for the report! Ideally we'd make sure XDE freed up its ports before restarting the server (usually this happens but it sounds like sometimes it's not), in the meantime if you click Open in Simulator again from XDE it will tell the simulator the new project URL and ports.

**Comment by JulianKingman** [comment]
I usually have to restart XDE and the simulator about half-a-dozen times in the right order to get them to line up, it seems like maybe a race condition where the simulator and XDE are not aware of the ip address that is being used/received.

**Comment by JulianKingman** [comment]
I get this message constantly, to the extent that it's difficult to open an app. Is there some secret to the timing and order of starting/restarting XDE and the app? It's worth mentioning that I'm not behind a proxy, and the client 'times out' just about instantly.

**Comment by JulianKingman** [comment]
I just noticed that when an old debugger window is open, the issue is pronounced.

**Comment by JulianKingman** [comment]
Is this just a problem for me? I get this error constantly, making it nearly unusable at times.

**Comment by ide** [comment]
I think this is affecting you much more than other people. I haven't heard about this issue very often.

When XDE chooses to use a new port (which it typically doesn't, possibly exacerbating this issue on your computer), you'll need to exit out of your project on the phone and then re-open it to get the latest project manifest, which includes info about the new ports to use. If you just click Refresh that won't work because the refresh button in the redbox just uses RN's internal refresh mechanism, which tries to redownload the JS from the URL it previously used.

**Comment by ccheever** [comment]
Also, the problem is almost definitely that the original port is still occupied somehow. XDE tries to use the lowest ports that are free starting at 19000. Figuring out what's going on probably means starting by figuring out why the original port doesn't get freed up on restart.

**Comment by JulianKingman** [comment]
Maybe because I have an older mac? (2011). I don't run other processes on the 19000 ports, so... Not sure where to start. Let me know how I can help debug.

**Comment by jesseruder** [comment]
It shouldn't be changing the ip address when you click "send to simulator", should only happen on "restart". Can you try running `lsof -i :PORT` on the old port to see if there's actually something running on it still?
