### ISSUE TITLE
[BUG] Error occurs when creating a new project on Expo XDE for Windows OS 

### ISSUE THREAD

**Issue by WendySanarwanto** [expo/xde#86]
Synopsis:
-----------
When creating a new project on Expo XDE on Windows 10-64 bit, the downloading process took time  before it shows `Downloading ... 0%` progress dialog with `Retry` button. 

![image](https://cloud.githubusercontent.com/assets/18456618/24253051/347d384e-101a-11e7-9aa2-b4281699fd47.png)

Clicking the `Retry` button, shows spinning progress little dialog for few seconds and then shows `Choose a template for your project` dialog again but with `EPERM` error message. 

![image](https://cloud.githubusercontent.com/assets/18456618/24253139/6df995cc-101a-11e7-9771-83489475199f.png)

Clicking the `Create button` will shows spinning progress little dialog and then back to the `Choose a template for your project` dialog with the error message again. 

Replication Steps:
--------------------
1. Install & run Expo XDE for windows 
2. Login using Expo account on the running Expo XDE app.
3. Click New project or open existing project.
4. On the `Choose a template for your project` , type in the project's name and then click `Create` button.
   Confirm that the issue explained in prior section occurs.

System Environments:
------------------------
- Windows 10 Pro , version 1703, Build 15058.0 (insider preview built with developer mode is turned on).

**Comment by flyweights** [comment]
mac , Same as above

**Comment by jesseruder** [comment]
I think the root cause here is that sometimes XDE has trouble connecting to the network. We're doing some work to use the Chromium network stack which should fix this issue.

**Comment by brentvatne** [comment]
tracking in https://github.com/expo/expo/issues/179
