### ISSUE TITLE
Couldn't connect to the server, check your internet connection.

### ISSUE THREAD

**Issue by flyweights** [expo/xde#87]
Are there any other way to download?

![image](https://cloud.githubusercontent.com/assets/12111609/24343217/d9593e0a-12f7-11e7-91a9-abea3c18fe38.png)

**Comment by dikaiosune** [comment]
Hi! Sorry for the delay here. You can download the [starter project directly](http://expo.io/--/api/v2/versions/download-template/blank), extract it, and open it in XDE.
