### ISSUE TITLE
Unable to open Android Emulator

### ISSUE THREAD

**Issue by CapitanRedBeard** [expo/xde#88]
#### Version
XDE: `Version 2.16.1 (2.16.1)`

Getting this error in the XDE: 
```
Couldn't start project on Android: Error running adb: No Android device found. Please connect a device and follow the instructions here to enable USB debugging:
https://developer.android.com/studio/run/device.html#developer-device-options. If you are using Genymotion go to Settings -> ADB, select "Use custom Android SDK tools", and point it at your Android SDK directory.
```
Running `exp path` produces:
```
[exp] Set XDE path to /home/user/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/emmett/Library/Android/sdk/tools:/Users/emmett/Library/Android/sdk/platform-tools
```

Running `echo $ANDROID_HOME` produces: `/Users/emmett/Library/Android/sdk`

I've set the Genymotion SDK to point to `/Users/emmett/Library/Android/sdk`
Opening the emulator (Google Nexus 5 - 5.0.0 - API 21) through Genymotion works fine, and I've set USB debugging on this emulator, although I don't think this matters for emulators.

Running  `adb devices` while I have the genymotion emulator open I receive: 
```
List of devices attached
192.168.56.101:5555	device
```
Running `/Applications/Genymotion.app/Contents/MacOS/tools/adb devices` while I have the genymotion emulator open I receive: 
```
List of devices attached
adb server version (39) doesn't match this client (36); killing...
error: could not install *smartsocket* listener: Address already in use
ADB server didn't ACK
* failed to start daemon *
error: cannot connect to daemon
```
Is it possible that XDE is expecting the genymotion adb while I am trying to use the android studio adb? If so how do I sync the two?

Thanks!

**Comment by jesseruder** [comment]
Thank you for the detailed report!

Do you have an old version of `exp`? That's my only thought for why this wouldn't be working. Also can you check your `~/.expo/state.json` file and make sure it has `"PATH": "/home/user/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/emmett/Library/Android/sdk/tools:/Users/emmett/Library/Android/sdk/platform-tools"` in it?

**Comment by CapitanRedBeard** [comment]
exp version is `37.0.1` which seems to be the latest. I can also confirm that `"PATH": "/home/user/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/emmett/Library/Android/sdk/tools:/Users/emmett/Library/Android/sdk/platform-tools"` is in my `~/.expo/state.json`

I'll keep playing around with it, I'll post back here if I find anything. 
Thanks!

**Comment by vayurobins** [comment]
Hi CapitanRedBeard. Did you ever find a solution this problem? I am having the same and am very stuck at moment. My exp version 40.0.2 and path is correct in state.json.

**Comment by TimbreApp** [comment]
Same here not working :(

**Comment by brentvatne** [comment]
Moved to https://github.com/expo/expo/issues/180 because we are consolidating issues onto expo/expo
