### ISSUE TITLE
"No Devices Connected" when running both IOS Simulator and Expo Client on android Galaxy

### ISSUE THREAD

**Issue by yellowspaceboots** [expo/xde#90]
I just wanted to see if this was an issue for anyone else. 12 hours ago I was getting logs for my redux actions in the log view and then this morning that stopped happening. No changes were made to my code. I noticed XDE is showing "No Connected Devices" but my app is functioning as expected in the simulator and on the Galaxy tablet. I have tried restarting XDE and also restarting the computer entirely. Thanks!

**Comment by terribleben** [comment]
Hi there,
1) What actions are you taking to open the app on your device?
2) Does your JS include `import Expo from 'expo';` at the top of the entry file?

**Comment by yellowspaceboots** [comment]
Hey @terribleben ! See below! Thanks for taking the time!

1. I am sending the link to my gmail account and clicking the link on the Galaxy to open in Expo Client. But even when I open the IOS simulator from XDE the app will load fine but no logs are seen. I am in development mode using Tunnel and exp.

2. Yes the main.js file I am importing Expo and using it `Expo.registerRootComponent(App)`

I have double checked to make sure I have the latest version of XDE installed and I do. I also started up a brand new project and threw a `console.log('test')` in the root components render function and nothing was logged to XDE's console.

Mac's console shows errors from Exponent over over and over reading 

> nw_connection_get_connected_socket_block_invoke Connection has no connected handler
TCP conn 0x61800019ad00 Failed : error 0:61 [61]

**Comment by jesseruder** [comment]
Hey @yellowspaceboots that's really odd. Are you using a tunnel url? It might help to close XDE, clear you project's `.expo` directory, and then open XDE again. If that doesn't work you could join us on slack: https://slack.expo.io. Might be easier to help there.

**Comment by yellowspaceboots** [comment]
Hey @jesseruder that worked! I cleared the .expo directory and started up XDE and all is as it should be. Thanks for your help and I will definitely check out the Slack channel! :)
