### ISSUE TITLE
React Native Packager message: 'yarn' is not recognized...

### ISSUE THREAD

**Issue by luferogo** [expo/xde#91]
Hi there, 

While loading the project generated by [CRNA](https://github.com/react-community/create-react-native-app), I am receiving this message:
![image](https://cloud.githubusercontent.com/assets/2007733/24736087/d96b972c-1a3a-11e7-8661-409b85135547.png)

Do you think this error is due some global installation/XDE setting? Or I should post the issue in CRNA repo?

**Comment by brentvatne** [comment]
Looks like this is fixed upstream now, as per https://github.com/facebook/react-native/pull/13355
