### ISSUE TITLE
Show packager port for debugging in VSCode

### ISSUE THREAD

**Issue by brentvatne** [expo/xde#92]
When cleaning up logs recently I removed the line that indicated what port the packager was running on. I didn't think this was useful information, but it turns out that it is indeed valuable for debugging with VSCode. ~You can still find the port by switching protocol to localhost, but we should expose it somewhere more obvious~ that is the manifest port.

If we can't think of anything better than a log message then perhaps putting the log back is enough.

**Comment by dikaiosune** [comment]
Even better, we should support https://github.com/react-community/create-react-native-app/issues/108 so that VSCode can just tell us where it expects the packager.
