### ISSUE TITLE
chmod - Operation not permitted | Linux

### ISSUE THREAD

**Issue by itsashis4u** [expo/xde#94]
I am trying to install xde on my linux machine. I am getting the following error
`chmod: changing permissions of ‘/home/ashish/.local/share/applications/mimeapps.list’: Operation not permitted`

**Comment by dikaiosune** [comment]
What steps did you take to install XDE? Did you download it from our website?

**Comment by itsashis4u** [comment]
Yes I downloaded it from your website.
And followed the instructions 

- On Linux, open with chmod a+x xde*.AppImage and ./xde*.AppImage

**Comment by ide** [comment]
Can you try `sudo chmod u+w ~/.local/share/applications/mimeapps.list`?

**Comment by itsashis4u** [comment]
@ide I will try and post the result.
