### ISSUE TITLE
Downalod Issue

### ISSUE THREAD

**Issue by abhitheawesomecoder** [expo/xde#96]
I tried to download xde but your server is so weak that every time download is getting disconnected. I am located in India. This is the link via which I am trying to download

https://xde-updates.exponentjs.com/download/linux-x86_64

Can you help me with an alternate download link or upload it on drop-box and share the file with me

**Comment by brentvatne** [comment]
Hello! This isn't related to our server being "weak" -- the download URL is redirected to the Github download link: https://github.com/expo/xde/releases

We shared a Dropbox link with you in Slack but I'm afraid if that doesn't work, this will only be one of many problems that you will encounter when using the project -- npm for example will be incredibly slow / likely unusable.
