### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by rrjanbiah** [expo/xde#97]
build fails in final `yarn start` in 32 bit Ubuntu MATE (trying to build as suggested in #89)

Attachment: [npm-debug.log.txt](https://github.com/expo/xde/files/930252/npm-debug.log.txt)

Error message:

>>>
yarn start v0.23.2
$ cross-env XDE_NPM_START=1 npm run _start 

> @ _start /home/raj/applications/xde
> concurrently --kill-others --raw "npm run webpack" "npm run app"

> @ webpack /home/raj/applications/xde
> node scripts/webpack

> @ app /home/raj/applications/xde
> gulp rebuild && npm run electron

[21:12:08] Requiring external module babel-register

> @ webpack-dev /home/raj/applications/xde
> webpack -w --env.dev

/home/raj/applications/xde/node_modules/electron/index.js:9
  throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
  ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> (/home/raj/applications/xde/node_modules/electron/index.js:9:9)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/raj/applications/xde/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/raj/applications/xde/gulp/build-tasks.js:3:1)

npm ERR! Linux 4.4.0-72-generic
npm ERR! argv "/home/raj/.nvm/versions/node/v6.10.2/bin/node" "/home/raj/.nvm/versions/node/v6.10.2/bin/npm" "run" "app"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ app: `gulp rebuild && npm run electron`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ app script 'gulp rebuild && npm run electron'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp rebuild && npm run electron
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/raj/applications/xde/npm-debug.log

npm ERR! Linux 4.4.0-72-generic
npm ERR! argv "/home/raj/.nvm/versions/node/v6.10.2/bin/node" "/home/raj/.nvm/versions/node/v6.10.2/bin/npm" "run" "_start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ _start: `concurrently --kill-others --raw "npm run webpack" "npm run app"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ _start script 'concurrently --kill-others --raw "npm run webpack" "npm run app"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently --kill-others --raw "npm run webpack" "npm run app"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/raj/applications/xde/npm-debug.log
error Command failed with exit code 1.
>>>

**Comment by dikaiosune** [comment]
> throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')

Did you try the step suggested by the error message?

**Comment by rrjanbiah** [comment]
> Did you try the step suggested by the error message?

That thrown `node_modules/electron` path not found error. `nvm install v6` didn't setup `node_modules/electron`. `npm install` did setup `node_modules/electron`, but it was throwing up lot of syntax errors.

So, I tried to do everything from the scratch and getting different errors now:

* [xde-log1.txt](https://github.com/expo/xde/files/933040/xde-log1.txt)
* [xde-log2.txt](https://github.com/expo/xde/files/933039/xde-log2.txt) (after launching new terminal)

Any suggestions will be highly helpful.

**Comment by rrjanbiah** [comment]
@dikaiosune Any hint please? Or, am I asking too basic?

**Comment by dikaiosune** [comment]
Hm, I'm not sure what would be causing that TypeError. Unfortunately we don't have enough resources to provide a lot of help and troubleshooting for building XDE from source :(. I'd recommend looking on the Electron repo for open issues and maybe looking at the script that produces that error.

**Comment by rrjanbiah** [comment]
For anyone watching this issue... posted to electron forum at https://discuss.atom.io/t/error-when-building-xde-from-source/42250

**Comment by brentvatne** [comment]
I'll close this because it indeed seems to be an issue with electron building on your machine. I'd try creating a simple electron project and debugging that way. Let me know if you find the solution!
