### ISSUE TITLE
Cannot use exp without an account

### ISSUE THREAD

**Issue by th0ma5w** [expo/xde#98]
Was wanting to use the software but don't want to create an account with any online service.

**Comment by ide** [comment]
You could use create-react-native-app if you want to use most of Expo without an account. exp requires an account because it lets you do things like send push notifications and publish your project, which require a developer account.

**Comment by th0ma5w** [comment]
Are the sources available for those features anywhere to run on my own server? Thank you for the prompt reply!

**Comment by ide** [comment]
The server isn't open source for some technical and product reasons (ex: we ensure that everyone's push notification credentials are encrypted and behind a VPN, our client code doesn't have to be infinitely backwards compatible with old servers). So if you wanted to run your own server you could use create-react-native-app and eject to bare React Native (and not use Expo). Like GitHub, Apple, Firebase, and other common developer services you need a dev account to use Expo services though.

These are some posts about Expo philosophy too:
Open Sourcing the Expo client: https://blog.expo.io/open-sourcing-the-exponent-client-9b37634c13d7#.n3xdmqq0j
Expo is Free (as in 🍺 and as in 💬): https://blog.expo.io/exponent-is-free-as-in-and-as-in-1d6d948a60dc

**Comment by th0ma5w** [comment]
Okay sounds good. I was very confused as I came from a prominent article that was featured recently but I couldn't find a way to use the software without the service. I think it is really great that the code to interact with the service is open, but that unfortunately isn't useful for me. Thanks again for your prompt replies and best of luck on your business.
