### ISSUE TITLE
No Devices Connected on linux

### ISSUE THREAD

**Issue by GZep** [expo/xde#99]
adb devices is working
/opt/android-sdk/ is chmod 777 recursively

```
$ adb devices
List of devices attached
08d84da1        device

$ echo $ANDROID_HOME
/opt/android-sdk/
```

Archlinux, all packages are updated

But Expo XDE shows "No Devices Connected" and no logs all time

**Comment by dikaiosune** [comment]
Is this after clicking on Device -> Open on Android?

**Comment by GZep** [comment]
When I'm clicking "Open on Android", the device just start running an app.
But "no device connected" showing all time independently and no logs available on the right side.

**Comment by brentvatne** [comment]
did you manage to figure out what was going on here @GZep?

**Comment by brentvatne** [comment]
please re-post this issue on https://github.com/expo/expo/issues if it is unresolved, thanks!
